/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import NextAuthSessionProvider from '@/providers/nextAuthSessionProvider'

import { getCssText } from '../styles'
import { globalStyles } from '../styles/global'

const roboto = Roboto({ style: ['normal'], weight: ['100', '300', '400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  globalStyles()

  return (
    <html lang="en">
      <head>
        {/* <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;700&display=swap" rel="stylesheet" /> */}
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body className={roboto.className}>
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
